# Generated by Django 4.0.4 on 2022-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('candidate_one', models.CharField(max_length=30)),
                ('candidate_two', models.CharField(max_length=30)),
                ('candidate_three', models.CharField(max_length=30)),
                ('candidate_one_count', models.IntegerField(default=0)),
                ('candidate_two_count', models.IntegerField(default=0)),
                ('candidate_three_count', models.IntegerField(default=0)),
            ],
        ),
    ]
