# Generated by Django 4.0.4 on 2022-06-28 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='close_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date close'),
        ),
        migrations.AddField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
