# Generated by Django 4.0.4 on 2022-07-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_candidate_poll_candidate_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='candidate_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='candidate_one_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='candidate_three',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='candidate_three_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='candidate_two',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='candidate_two_count',
        ),
    ]
