# Generated by Django 4.0.4 on 2022-07-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_remove_poll_candidate_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='candidate_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images'),
        ),
    ]
