# Generated by Django 4.0.4 on 2022-07-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_choice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
