# Generated by Django 4.0.4 on 2022-07-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_choice_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='candidate_image',
        ),
    ]
