# Generated by Django 4.0.4 on 2022-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='candidate_count',
        ),
        migrations.AddField(
            model_name='choice',
            name='candidate_count',
            field=models.IntegerField(default=0),
        ),
    ]
